### PR TITLE
Add data squashing

### PR DESCRIPTION
**Pull request by zStupan**
- Updated dependencies
- Added Data Squashing

### CODE REVIEW

**Review by firefly-cpp — APPROVED** [review]
This is amazing. Thanks, @zStupan!

**Comment by firefly-cpp** [comment]
Are results similar to the results obtained by the conference paper?

**Comment by zStupan** [comment]
@firefly-cpp I tested with Abalone, and the results for cosine similarity are exactly the same. There's a slight difference with euclidean distance because of how the distance between categorical attributes is measured. Here I've just done one hot encoding, so the distance between different categories is 1. In uARMSolver it's 1/num_categories.

**Comment by firefly-cpp** [comment]
Perfect!

**Pull request merged**
